version: 2.1
# Use a package of configuration called an orb.

orbs:
  docker: circleci/docker@1.3.0

workflows:
  docker_publish:
    jobs:
      - docker/publish:
          image: randypitcherii/snowflake_data_profiler
          docker-password: DOCKERHUB_KEY
